### ISSUE TITLE
Does this package actually work

### ISSUE THREAD

**Issue by donnywals** [appspector/Xcode-InstrumentsPackage#1]
Not sure if this is the best way to ask, but here it goes anyway.
I'm trying to set up my own instrument but I can't get any data to show. The lack of documentation is making it hard for me to debug what could be wrong so was hoping this instrument works and maybe you could give come pointers towards documentation I might have missed..

thanks!

**Comment by deszip** [comment]
It didn't work when I've published it, I've just updated code and checked on the recent Xcode, it still doesn't work :( But now I can see my events in Instruments Inspector. I'm discussing this with Kacper, Apple guy from 410 wwdc session and will update repo when it will be fixed.

**Comment by donnywals** [comment]
Awesome! 👍
