### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by Gamedevolop** [appspector/Xcode-InstrumentsPackage#3]
What is this for?

is an App Monitor or something? 
What can I do with this? 
can you give us more info, please 

Im looking for an App monitor to Monitor (Cpu/fps/MR)

**Comment by xNekOIx** [comment]
@Gamedevolop it is a sample project related to [the article @ AppSpector's blog](https://medium.com/appspector/building-custom-instruments-package-9d84fd9339b6)

**Comment by deszip** [comment]
Hi @Gamedevolop, as @xNekOIx said this is a sample project illustrating the usage of Xcode custom instruments packages, you can refer [WWDC session 410](https://developer.apple.com/videos/play/wwdc2018/410/) for more info.

If you need performance monitoring you can use our product [AppSpector](https://appspector.com) for this.

Closing this now, if you have more questions feel free to ping us at [Slack](https://slack.appspector.com).

**Comment by Gamedevolop** [comment]
I see Thank you
